GET http://localhost:8080
###

GET http://localhost:8080/movies
###

GET http://localhost:8080/movies/1
###

POST http://localhost:8080/movies
content-Type: application/json

    {
        "movie":
            {
                "id": 6,
                "name": "test",
                "year": 2022,
                "rating": 10
            }
    }
###

PUT http://localhost:8080/movies/5
content-Type: application/json

{
    "year": 2004,
    "rating": 8
}
###

DELETE http://localhost:8080/movies/6